### ISSUE TITLE
IDT有问题

### ISSUE THREAD

**Issue by bobcao3** [satgo1546/frogimine#1]
一旦接受到IRQ就崩溃了

**Comment by satgo1546** [comment]
这个问题很麻烦，因为我也不知道怎么解决。

**Comment by bobcao3** [comment]
https://github.com/IcebergOS/Cryst
里面有实现了的IDT，

**Comment by satgo1546** [comment]
我们都知道Cryst和Frogimine是可以互相参考的……

总之，这个问题等必须要解决的时候再解决吧。（虽然现在已经是必须要解决的了）

**Comment by satgo1546** [comment]
已解决。然而并没有参考Cryst。

参照 https://github.com/satgo1546/frogimine/releases/tag/v0.04 。
